# Generated by Django 5.0.6 on 2024-05-31 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Commodities",
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "cell_phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("extension_agent", "Extension Agent"),
                            ("chairman", "Chairman"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("number_of_vendors", models.IntegerField(default=0)),
                ("market_day_interval", models.SmallIntegerField(default=4)),
                (
                    "reference_mkt_date",
                    models.DateField(verbose_name="confirmed market date"),
                ),
                (
                    "accepted_payment_method",
                    models.CharField(
                        choices=[
                            ("CH", "Cash"),
                            ("CC", "Credit Card"),
                            ("POS", "Point of Sale"),
                            ("ATM", "ATM Onsite"),
                            ("ATM_nearby", "ATM within 5 minutes walk"),
                            ("BT", "Bank Transfer"),
                        ],
                        default="CH",
                        max_length=100,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "local_govt_area",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("town", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, max_length=9, null=True)),
                ("longitude", models.FloatField(blank=True, max_length=9, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contact_person",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market",
                        to="market.contactperson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketCommodityPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="market.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="market.market",
                    ),
                ),
            ],
            options={
                "unique_together": {("market", "commodity", "date")},
            },
        ),
        migrations.AddField(
            model_name="market",
            name="market_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="markets",
                through="market.MarketCommodityPrice",
                to="market.commodity",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_market_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("longitude", "latitude"), name="unique_market_location"
            ),
        ),
    ]
