# Generated by Django 5.0.6 on 2024-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="commodity",
            constraint=models.UniqueConstraint(
                fields=("crop_name",), name="unique_crop_name"
            ),
        ),
    ]
