# Generated by Django 5.0.6 on 2024-06-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_commodity_unique_crop_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="market",
            old_name="street",
            new_name="display_address",
        ),
    ]
