# Generated by Django 5.1 on 2024-09-02 14:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgroVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=14, null=True, region=None, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("addressof_business", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
                ("lga", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("verification_status", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
