# Generated by Django 5.1 on 2024-08-24 23:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgroVendor",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("addressof_business", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
                ("lga", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("verification_status", models.BooleanField(default=False)),
            ],
        ),
    ]
