# Generated by Django 5.1.1 on 2024-10-01 23:23

import datetime
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(default="Market Description")),
                ("number_of_vendors", models.IntegerField(default=0)),
                (
                    "operating_hours",
                    models.CharField(default="8:00 AM - 5:00 PM", max_length=50),
                ),
                (
                    "market_frequency",
                    models.SmallIntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "last_market_day",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Confirmed last market date",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("MA", "Market Agent"), ("ML", "Market Leader")],
                        default="MA",
                        max_length=255,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarketDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("events", models.TextField(default="Market Event")),
                ("date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CC", "Credit Card"),
                            ("MM", "Mobile Money"),
                            ("BT", "Bank Transfer"),
                            ("POS", "Point of Sale"),
                            ("ATM", "ATM on site"),
                            ("CASH", "Cash"),
                        ],
                        default="CASH",
                        max_length=4,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "extra",
                    models.CharField(
                        default="",
                        help_text="eg. brown beans, shelled groudnut",
                        max_length=50,
                    ),
                ),
                ("local_name", models.CharField(default="", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PN", "Pulse and Nuts"),
                            ("CT", "Cereals and Tubers"),
                            ("OF", "Oil and Fats"),
                            ("MFE", "Meat, Fish and Eggs"),
                            ("MD", "Milk and Dairy"),
                            ("VF", "Vegetable and Fruits"),
                            ("NF", "Non Food"),
                            ("MS", "Miscellaneous Food"),
                        ],
                        default="CT",
                        max_length=3,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("BAG", "100 KG"),
                            ("50KG", "50 KG"),
                            ("100T", "100 Tubers"),
                            ("25ltr", "25 liters"),
                        ],
                        default="BAG",
                        max_length=5,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "commodities",
            },
        ),
        migrations.CreateModel(
            name="ProducePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("W", "Wholesale"), ("R", "Retail")],
                        default="W",
                        max_length=1,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("town", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.FloatField(blank=True, max_length=9, null=True)),
                ("longitude", models.FloatField(blank=True, max_length=9, null=True)),
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="market.market",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="market",
            name="contact_person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="market",
                to="market.contactperson",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactperson",
            constraint=models.UniqueConstraint(
                fields=("phonenumber", "email"), name="unique_contact_person"
            ),
        ),
        migrations.AddField(
            model_name="marketday",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_day",
                to="market.market",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="payment_methods",
            field=models.ManyToManyField(to="market.paymentmethod"),
        ),
        migrations.AddConstraint(
            model_name="produce",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_commodity_name"
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="produce_items",
            field=models.ManyToManyField(to="market.produce"),
        ),
        migrations.AddField(
            model_name="produceprice",
            name="market_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produce_price",
                to="market.marketday",
            ),
        ),
        migrations.AddField(
            model_name="produceprice",
            name="produce",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produce_price",
                to="market.produce",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cities_light.country",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="local_govt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cities_light.subregion",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cities_light.region",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketday",
            constraint=models.UniqueConstraint(
                fields=("market", "date"), name="unique_market_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_market_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="produceprice",
            constraint=models.UniqueConstraint(
                fields=("produce", "market_day"), name="unique_produce_price"
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"), name="unique_latitude_longitude"
            ),
        ),
    ]
