# Generated by Django 5.0.6 on 2024-06-27 14:39

import django.db.models.deletion
from django.db import migrations, models

import market.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("extension_agent", "Extension Agent"),
                            ("chairman", "Chairman"),
                        ],
                        default="extension_agent",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "display_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("town", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.FloatField(blank=True, max_length=9, null=True)),
                ("longitude", models.FloatField(blank=True, max_length=9, null=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("number_of_vendors", models.IntegerField(default=0)),
                (
                    "operating_hours",
                    models.CharField(default="8:00 AM - 5:00 PM", max_length=50),
                ),
                ("market_day_interval", models.SmallIntegerField(default=4)),
                (
                    "reference_mkt_date",
                    models.DateField(verbose_name="confirmed market date"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarketImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="market/images/%Y/%m/%d/",
                        validators=[market.validators.validate_file_size],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mkt_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.IntegerField(
                        choices=[
                            (1, "Cash"),
                            (2, "Credit Card"),
                            (3, "Point of Sale"),
                            (4, "ATM Onsite"),
                            (5, "ATM within 5 minutes walk"),
                            (6, "Bank Transfer"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("WHEAT", "Wheat"),
                            ("MILLED RICE", "Milled Rice"),
                            ("PADDY RICE", "Paddy Rice"),
                            ("BROWN_COWPEA", "Brown Cowpea"),
                            ("WHITE COWPEA", "White Cowpea"),
                            ("WHITE MAIZE", "White Maize"),
                            ("YELLOW MAIZE", "Yellow Maize"),
                            ("SOYBEAN", "Soybean"),
                            ("WHITE SORGHUM", "White Sorghum"),
                            ("YELLOW_SORGHUM", "Yellow Sorghum"),
                            ("SWEET POTATOES", "Sweet Potatoes"),
                            ("IRISH POTATOES", "Irish Potatoes"),
                            ("ONION", "Onion"),
                            ("TOMATO", "Tomato"),
                            ("DRIED TOMATOES", "Dry Tomatoes"),
                            ("PEPPER", "Pepper"),
                        ],
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("local_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "unit",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "100 Kg Sack"),
                            (2, "50 Kg Basket"),
                            (3, "50 Kg Sack"),
                            (4, "25 Kg Sack"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products",
            },
        ),
        migrations.AddConstraint(
            model_name="contactperson",
            constraint=models.UniqueConstraint(
                fields=("phone", "email"), name="unique_contact_person"
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="contact_person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="markets",
                to="market.contactperson",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.country",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.region",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="sub_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.subregion",
            ),
        ),
        migrations.AddField(
            model_name="marketimage",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="market_images",
                to="market.market",
            ),
        ),
        migrations.AddField(
            model_name="marketproduct",
            name="market",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="market_product",
                to="market.market",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="accepted_payment_methods",
            field=models.ManyToManyField(
                blank=True, related_name="markets", to="market.paymentmethod"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "local_name"), name="unique_name"
            ),
        ),
        migrations.AddField(
            model_name="marketproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="market_product",
                to="market.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_market_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketproduct",
            constraint=models.UniqueConstraint(
                fields=("product", "market", "mkt_date"), name="unique_item"
            ),
        ),
    ]
