# Generated by Django 5.1.1 on 2024-09-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="market",
            old_name="display_address",
            new_name="street_address",
        ),
    ]
