# Generated by Django 5.1 on 2024-09-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="market",
            name="accepted_payment_methods",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
