# Generated by Django 5.1.1 on 2024-09-22 03:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketimage",
            name="market",
        ),
        migrations.AlterModelOptions(
            name="produce",
            options={"verbose_name_plural": "products"},
        ),
        migrations.RemoveConstraint(
            model_name="marketday",
            name="unique_market_day",
        ),
        migrations.RenameField(
            model_name="marketday",
            old_name="mkt_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="market",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="market",
            name="reference_mkt_date",
        ),
        migrations.AddField(
            model_name="market",
            name="image",
            field=models.ImageField(blank=True, upload_to="market_images/"),
        ),
        migrations.AddField(
            model_name="market",
            name="last_market_day",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Confirmed last market date",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="market_frequency",
            field=models.SmallIntegerField(
                default=4, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="marketday",
            name="events",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="produceprice",
            name="market_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produce_price",
                to="market.marketday",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketday",
            constraint=models.UniqueConstraint(
                fields=("market", "date"), name="unique_market_day"
            ),
        ),
        migrations.DeleteModel(
            name="MarketImage",
        ),
    ]
