# Generated by Django 5.1.1 on 2024-10-02 06:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="phonenumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=14, region=None, unique=True
            ),
        ),
    ]
