# Generated by Django 5.1.1 on 2024-10-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produce",
            options={"verbose_name_plural": "commodities"},
        ),
        migrations.RemoveConstraint(
            model_name="produce",
            name="unique_name",
        ),
        migrations.AddField(
            model_name="produce",
            name="detail",
            field=models.CharField(
                default="", help_text="eg. brown beans, shelled groudnut", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="produceprice",
            name="price_type",
            field=models.CharField(
                choices=[("W", "Wholesale"), ("R", "Retail")], default="W", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="produce",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="produce",
            name="unit",
            field=models.CharField(
                choices=[
                    ("BAG", "100 KG"),
                    ("50KG", "50 KG"),
                    ("100T", "100 Tubers"),
                    ("25ltr", "25 liters"),
                ],
                default="BAG",
                max_length=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="produce",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_commodity_name"
            ),
        ),
    ]
