# Generated by Django 5.1 on 2024-08-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                choices=[
                    ("WHEAT", "Wheat"),
                    ("MILLET", "Millet"),
                    ("GINGER", "Ginger"),
                    ("PADDY RICE", "Paddy Rice"),
                    ("BROWN_COWPEA", "Brown Cowpea"),
                    ("WHITE COWPEA", "White Cowpea"),
                    ("WHITE MAIZE", "White Maize"),
                    ("YELLOW MAIZE", "Yellow Maize"),
                    ("WHITE SORGHUM", "White Sorghum"),
                    ("YELLOW_SORGHUM", "Yellow Sorghum"),
                    ("SESAME", "Sesame"),
                    ("GROUNDNUT", "Groundnut"),
                    ("SOYBEAN", "Soybean"),
                    ("IRISH POTATO", "Irish Potatoes"),
                    ("SWEET POTATO", "Sweet Potatoes"),
                    ("YAM", "Yam"),
                    ("CASSAVA", "Cassava"),
                    ("ONION", "Onion"),
                    ("OKRA", "Okra"),
                    ("TOMATO", "Fresh Tomato"),
                    ("PEPPER", "Fresh Pepper"),
                    ("DRIED TOMATOES", "Dry Tomatoes"),
                    ("DRIED PEPPER", "Dry Pepper"),
                    ("MILLED RICE", "Milled Rice"),
                    ("GARRI", "Garri"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "100 Kg Sack"),
                    (2, "50 Kg Basket"),
                    (3, "50 Kg Sack"),
                    (4, "25 Kg Sack"),
                ],
                default=1,
                null=True,
            ),
        ),
    ]
