# Generated by Django 5.0.6 on 2024-06-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactperson",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
