# Generated by Django 5.0.6 on 2024-06-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_rename_phone_contactperson_phone_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contactperson",
            name="unique_contact_person",
        ),
        migrations.AddConstraint(
            model_name="contactperson",
            constraint=models.UniqueConstraint(
                fields=("phone_number", "email"), name="unique_contact_person"
            ),
        ),
    ]
