# Generated by Django 5.1.1 on 2024-09-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_market_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketday",
            name="events",
            field=models.TextField(default="Market Event"),
        ),
        migrations.AlterField(
            model_name="marketpaymentmethod",
            name="description",
            field=models.CharField(default="Charges varies market day", max_length=255),
        ),
        migrations.AlterField(
            model_name="produceprice",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
