# Generated by Django 5.1 on 2024-08-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_product_name_alter_product_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
