# Generated by Django 5.1.1 on 2024-09-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_remove_marketimage_market_alter_produce_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="market",
            old_name="stree_address",
            new_name="street_address",
        ),
    ]
