# Generated by Django 5.1.1 on 2024-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_contactperson_phonenumber"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contactperson",
            name="unique_contact_person",
        ),
        migrations.RenameField(
            model_name="contactperson",
            old_name="phonenumber",
            new_name="phone_number",
        ),
        migrations.AddConstraint(
            model_name="contactperson",
            constraint=models.UniqueConstraint(
                fields=("phone_number", "email"), name="unique_contact_person"
            ),
        ),
    ]
