# Generated by Django 5.1 on 2024-09-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_remove_market_accepted_payment_methods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketday",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="market.market"
            ),
        ),
    ]
