# Generated by Django 5.1.1 on 2024-10-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_produce_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produce",
            old_name="detail",
            new_name="extra",
        ),
    ]
