# Generated by Django 5.1 on 2024-08-29 22:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_contactperson_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contactperson",
            name="unique_contact_person",
        ),
        migrations.RemoveField(
            model_name="contactperson",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="market",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="market",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="marketimage",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="marketimage",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="marketproduct",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="marketproduct",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="contactperson",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="marketproduct",
            name="mkt_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name="contactperson",
            constraint=models.UniqueConstraint(
                fields=("phone", "email"), name="unique_contact_person"
            ),
        ),
    ]
