# Generated by Django 5.1.1 on 2024-09-27 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_marketday_events_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CC", "Credit Card"),
                            ("MM", "Mobile Money"),
                            ("BT", "Bank Transfer"),
                            ("POS", "Point of Sale"),
                            ("ATM", "ATM on site"),
                            ("CASH", "Cash"),
                        ],
                        default="CASH",
                        max_length=4,
                    ),
                ),
                (
                    "markets",
                    models.ManyToManyField(
                        through="market.MarketPaymentMethod", to="market.market"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="marketpaymentmethod",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="market.paymentmethod"
            ),
        ),
    ]
