# Generated by Django 5.1.1 on 2024-09-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_rename_stree_address_market_street_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="market",
            name="image",
        ),
    ]
