# Generated by Django 5.1 on 2024-09-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_marketday_market"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketday",
            name="mkt_date",
            field=models.DateField(),
        ),
    ]
