# Generated by Django 5.1 on 2024-08-29 22:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_remove_contactperson_unique_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None
            ),
        ),
    ]
