# Generated by Django 5.1.1 on 2024-10-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_rename_detail_produce_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produce",
            name="category",
            field=models.CharField(
                choices=[
                    ("PN", "Pulse and Nuts"),
                    ("CT", "Cereals and Tubers"),
                    ("OF", "Oil and Fats"),
                    ("MFE", "Meat, Fish and Eggs"),
                    ("MD", "Milk and Dairy"),
                    ("VF", "Vegetable and Fruits"),
                    ("NF", "Non Food"),
                    ("MS", "Miscellaneous Food"),
                ],
                default="CT",
                max_length=3,
            ),
        ),
    ]
