# Generated by Django 5.1.1 on 2024-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_paymentmethod_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="markets",
        ),
        migrations.AddField(
            model_name="market",
            name="payment_methods",
            field=models.ManyToManyField(to="market.paymentmethod"),
        ),
        migrations.DeleteModel(
            name="MarketPaymentMethod",
        ),
    ]
