# Generated by Django 5.1.1 on 2024-09-22 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_marketday_market"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="contact_person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="market",
                to="market.contactperson",
            ),
        ),
    ]
