# Generated by Django 5.1.1 on 2024-09-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_remove_paymentmethod_markets_market_payment_methods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="type",
            field=models.CharField(
                choices=[
                    ("CC", "Credit Card"),
                    ("MM", "Mobile Money"),
                    ("BT", "Bank Transfer"),
                    ("POS", "Point of Sale"),
                    ("ATM", "ATM on site"),
                    ("CASH", "Cash"),
                ],
                default="CASH",
                max_length=4,
                unique=True,
            ),
        ),
    ]
