# Generated by Django 5.1.1 on 2024-09-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_alter_market_contact_person"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="produce",
            name="unique_name",
        ),
        migrations.AddConstraint(
            model_name="produce",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_name"),
        ),
    ]
