# Generated by Django 5.1.1 on 2024-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_alter_paymentmethod_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="produce_items",
            field=models.ManyToManyField(to="market.produce"),
        ),
    ]
