# Generated by Django 5.1.1 on 2024-09-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_market_produce_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produce",
            name="unit",
            field=models.IntegerField(
                choices=[(1, "100 Kg Sack"), (2, "50 Kg Basket"), (3, "50 Kg Sack")],
                default=1,
            ),
        ),
    ]
