# Generated by Django 5.1.1 on 2024-09-23 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_remove_produce_unique_name_produce_unique_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produce",
            options={"verbose_name_plural": "produce"},
        ),
        migrations.CreateModel(
            name="MarketPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CC", "Credit Card"),
                            ("MM", "Mobile Money"),
                            ("BT", "Bank Transfer"),
                            ("POS", "Point of Sale"),
                            ("ATM", "ATM on site"),
                            ("CASH", "Cash"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.market"
                    ),
                ),
            ],
            options={
                "unique_together": {("market", "payment_method")},
            },
        ),
    ]
