# Generated by Django 5.1.1 on 2024-09-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_alter_produce_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produce",
            name="local_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
