# Generated by Django 5.1 on 2024-09-01 00:06

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_alter_contactperson_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactperson",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="contactperson",
            old_name="updated_on",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="market",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="marketimage",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketimage",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="marketproduct",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketproduct",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=14, null=True, region=None, unique=True
            ),
        ),
    ]
