# Generated by Django 5.1.1 on 2024-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_alter_produce_local_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produce",
            name="unit",
            field=models.IntegerField(
                choices=[(1, "100 Kg"), (2, "Basket"), (3, "50 Kg")], default=3
            ),
        ),
    ]
