# Generated by Django 5.0.6 on 2024-06-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "education",
                    models.IntegerField(
                        choices=[
                            (1, "None or did not complete primary school"),
                            (2, "Completed primary school"),
                            (3, "Completed secondary school"),
                            (4, "Completed higher education"),
                            (5, "Religious or informal education"),
                            (888, "Don't know"),
                            (999, "Refused"),
                        ]
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("verification_status", models.BooleanField(default=False)),
                (
                    "means_of_identification",
                    models.CharField(
                        choices=[
                            ("NID", "National ID"),
                            ("PAS", "Passport"),
                            ("DL", "Driver's License"),
                        ],
                        default="NID",
                        max_length=3,
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_photo",
                    models.FileField(
                        blank=True, null=True, upload_to="identification_proof/"
                    ),
                ),
                (
                    "captured_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="captured_photo/"
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("farmsize", models.DecimalField(decimal_places=2, max_digits=10)),
                ("points", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("SH", "Smallholder"),
                            ("SMH", "Small to Medium Holder"),
                        ],
                        default="SMH",
                        max_length=3,
                    ),
                ),
                (
                    "agricultural_activities",
                    models.IntegerField(
                        choices=[
                            (1, "Crop Producer"),
                            (2, "Livestock Producer"),
                            (3, "Crop and Livestock Producer"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmersAccountDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                ("account_type", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FarmersCooperative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("registeration_date", models.DateField(auto_now_add=True)),
                ("registration_number", models.CharField(max_length=255)),
                ("verification_status", models.BooleanField(default=False)),
                ("number_of_members", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FieldExtensionOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "education",
                    models.IntegerField(
                        choices=[
                            (1, "None or did not complete primary school"),
                            (2, "Completed primary school"),
                            (3, "Completed secondary school"),
                            (4, "Completed higher education"),
                            (5, "Religious or informal education"),
                            (888, "Don't know"),
                            (999, "Refused"),
                        ]
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("verification_status", models.BooleanField(default=False)),
                (
                    "means_of_identification",
                    models.CharField(
                        choices=[
                            ("NID", "National ID"),
                            ("PAS", "Passport"),
                            ("DL", "Driver's License"),
                        ],
                        default="NID",
                        max_length=3,
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_photo",
                    models.FileField(
                        blank=True, null=True, upload_to="identification_proof/"
                    ),
                ),
                (
                    "captured_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="captured_photo/"
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaleTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("transaction_date", models.DateField(auto_now_add=True)),
                ("points_earned", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SubsidyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "sponsor",
                    models.CharField(
                        choices=[
                            ("M", "State Government"),
                            ("F", "Federal Government"),
                            ("N", "Non Governmental Organization"),
                        ],
                        max_length=1,
                    ),
                ),
                ("objective", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("eligibility_criteria", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("number_of_beneficiaries", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CultivatedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cropping_system",
                    models.IntegerField(
                        choices=[
                            (1, "Mono Cropping"),
                            (2, "Multi Cropping"),
                            (3, "Mixed Cropping"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "field_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "crop_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("crop_planting_date", models.DateField(blank=True, null=True)),
                ("crop_harvest_date", models.DateField(blank=True, null=True)),
                (
                    "crop_harvest_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("town", models.CharField(max_length=255)),
                ("local_govt_area", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("date_captured", models.DateField(auto_now_add=True)),
                ("soil_test_date", models.DateField(blank=True, null=True)),
                (
                    "test_results_file",
                    models.FileField(blank=True, null=True, upload_to="soil_tests/"),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="market.commodity",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cultivated_fields",
                        to="farmers.farmer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="farmer",
            name="account_number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="farmer",
                to="farmers.farmersaccountdetail",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="cooperative_society",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="farmers.farmerscooperative",
            ),
        ),
        migrations.CreateModel(
            name="FarmerSubsidy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redemption_date", models.DateField(auto_now_add=True)),
                (
                    "amount_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farmer"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fieldextensionofficer",
            constraint=models.UniqueConstraint(
                fields=("identification_number",), name="unique_feo_id_number"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="field_extension_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="farmer",
                to="farmers.fieldextensionofficer",
            ),
        ),
        migrations.AddField(
            model_name="saletransaction",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="farmers.farmer"
            ),
        ),
        migrations.AddField(
            model_name="saletransaction",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="market.market"
            ),
        ),
        migrations.AddField(
            model_name="saletransaction",
            name="produce",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="market.commodity"
            ),
        ),
        migrations.AddField(
            model_name="farmersubsidy",
            name="subsidy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmers_subsidy",
                to="farmers.subsidyprogram",
            ),
        ),
        migrations.AddConstraint(
            model_name="cultivatedfield",
            constraint=models.UniqueConstraint(
                fields=("field_name",), name="unique_field_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="farmer",
            constraint=models.UniqueConstraint(
                fields=("identification_number",), name="unique_farmer_id_number"
            ),
        ),
    ]
