# Generated by Django 5.0.6 on 2024-06-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldextensionofficer",
            name="slug",
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to="farmers.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to="market.market",
            ),
        ),
    ]
