# Generated by Django 5.1.1 on 2024-09-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agrovendor",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cities_light.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cities_light.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fieldextensionofficer",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cities_light.country",
            ),
            preserve_default=False,
        ),
    ]
