# Generated by Django 5.1.1 on 2024-09-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
        ("market", "0005_alter_marketday_mkt_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agrovendor",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="agrovendor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="agrovendor",
            name="lga",
        ),
        migrations.RemoveField(
            model_name="agrovendor",
            name="state",
        ),
        migrations.AddField(
            model_name="agrovendor",
            name="unique_id",
            field=models.CharField(default="UNIQUEID!", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_purchases",
                to="farmers.agrovendor",
            ),
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="farmers.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="market.market",
            ),
        ),
    ]
