# Generated by Django 5.1.1 on 2024-09-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="verification_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="state_of_origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cities_light.region",
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="state_of_residence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cities_light.region",
            ),
        ),
        migrations.AlterField(
            model_name="fieldextensionofficer",
            name="state_of_origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cities_light.region",
            ),
        ),
        migrations.AlterField(
            model_name="fieldextensionofficer",
            name="state_of_residence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cities_light.region",
            ),
        ),
    ]
