# Generated by Django 5.0.6 on 2024-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SaleTransaction",
            new_name="FarmersMarketTransaction",
        ),
        migrations.AddField(
            model_name="farmer",
            name="blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farmerscooperative",
            name="blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="means_of_identification",
            field=models.CharField(
                choices=[
                    ("ND", "National ID"),
                    ("IP", "International Passport"),
                    ("DL", "Driver's License"),
                ],
                default="ND",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="fieldextensionofficer",
            name="means_of_identification",
            field=models.CharField(
                choices=[
                    ("ND", "National ID"),
                    ("IP", "International Passport"),
                    ("DL", "Driver's License"),
                ],
                default="ND",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="FarmerSubsidy",
        ),
        migrations.DeleteModel(
            name="SubsidyProgram",
        ),
    ]
