# Generated by Django 5.1 on 2024-08-25 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("farmers", "0002_crop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="lga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cities_light.subregion",
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="farmsize",
            field=models.CharField(
                choices=[
                    ("<1", "<1 Hectare"),
                    ("1-3", "1-3 Hectares"),
                    ("3-5", "3-5 Hectares"),
                    (">5", ">5 Hectares"),
                ],
                default="1-3",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="state_of_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cities_light.region",
            ),
        ),
        migrations.AlterField(
            model_name="fieldextensionofficer",
            name="state_of_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cities_light.region",
            ),
        ),
    ]
