# Generated by Django 5.1.1 on 2024-09-28 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0002_agrovendor_country_farmer_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="earned_points",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
