# Generated by Django 5.0.6 on 2024-06-27 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0002_fieldextensionofficer_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
