# Generated by Django 5.1.1 on 2024-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0002_remove_agrovendor_contact_person_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farmersinputtransaction",
            name="unique_receipt_identifier",
        ),
        migrations.AddConstraint(
            model_name="farmersinputtransaction",
            constraint=models.UniqueConstraint(
                fields=("receipt_identifier",),
                name="unique_receipt_identifier",
                violation_error_message="Receipt already exist",
            ),
        ),
    ]
