# Generated by Django 5.1.1 on 2024-09-29 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0003_alter_farmer_earned_points_alter_farmer_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="earned_points",
            field=models.IntegerField(
                default=0,
                editable=False,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="is_verified",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
