# Generated by Django 5.1 on 2024-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0003_farmer_lga_alter_farmer_farmsize_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="verification_status",
        ),
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="receipt_identifier",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="redemption_date",
            field=models.DateField(),
        ),
    ]
