# Generated by Django 5.1.1 on 2024-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0004_alter_farmer_earned_points_alter_farmer_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="has_input_transaction",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="farmer",
            name="has_market_transaction",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
