# Generated by Django 5.1 on 2024-08-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0004_remove_farmer_verification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="receipt_identifier",
            field=models.CharField(
                blank=True, editable=False, max_length=255, unique=True
            ),
        ),
    ]
