# Generated by Django 5.0.6 on 2024-06-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0004_badge_userbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="name",
            field=models.CharField(
                choices=[("B", "Bronze"), ("S", "Silver"), ("G", "Gold")],
                default="B",
                max_length=255,
            ),
        ),
    ]
