# Generated by Django 5.1.1 on 2024-09-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_farmer_has_input_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="has_input_transaction",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="has_market_transaction",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
