# Generated by Django 5.1 on 2024-08-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_alter_farmersinputtransaction_receipt_identifier"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="receipt_identifier",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="farmersinputtransaction",
            constraint=models.UniqueConstraint(
                fields=("receipt_identifier",), name="unique_receipt_identifier"
            ),
        ),
    ]
