# Generated by Django 5.0.6 on 2024-06-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_alter_badge_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="image",
            field=models.ImageField(upload_to="farmers/badges/"),
        ),
    ]
