# Generated by Django 5.0.6 on 2024-06-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0006_alter_badge_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cultivatedcrop",
            name="crop",
            field=models.CharField(default="Wheat", max_length=255),
        ),
    ]
