# Generated by Django 5.1 on 2024-08-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0006_alter_farmersinputtransaction_receipt_identifier_and_more"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farmersinputtransaction",
            name="unique_receipt_identifier",
        ),
        migrations.AddConstraint(
            model_name="farmersinputtransaction",
            constraint=models.UniqueConstraint(
                fields=("receipt_identifier",),
                name="unique_receipt_identifier",
                violation_error_message="Receipt already exist",
            ),
        ),
    ]
