# Generated by Django 5.1.1 on 2024-09-30 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0007_alter_farmer_has_input_transaction_and_more"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_transaction",
                to="farmers.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="points_earned",
            field=models.IntegerField(
                default=0,
                editable=False,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_transaction",
                to="farmers.agrovendor",
            ),
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mkt_transaction",
                to="farmers.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mkt_transaction",
                to="market.market",
            ),
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="points_earned",
            field=models.IntegerField(
                default=1,
                editable=False,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
