# Generated by Django 5.1 on 2024-08-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0007_remove_farmersinputtransaction_unique_receipt_identifier_and_more",
        ),
        ("market", "0003_alter_contactperson_email"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farmersinputtransaction",
            name="unique_receipt_identifier",
        ),
        migrations.AddConstraint(
            model_name="farmersinputtransaction",
            constraint=models.UniqueConstraint(
                fields=("receipt_number", "vendor"),
                name="unique_receipt_identifier",
                violation_error_message="Receipt already exist",
            ),
        ),
        migrations.AddConstraint(
            model_name="farmersmarkettransaction",
            constraint=models.UniqueConstraint(
                fields=("farmer", "market", "produce", "transaction_date"),
                name="unique_transaction_id",
                violation_error_message="Transaction already exist",
            ),
        ),
    ]
