# Generated by Django 5.1 on 2024-08-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0008_remove_farmersinputtransaction_unique_receipt_identifier_and_more",
        ),
        ("market", "0003_alter_contactperson_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farmersmarkettransaction",
            name="unique_transaction_id",
        ),
        migrations.AddConstraint(
            model_name="farmersmarkettransaction",
            constraint=models.UniqueConstraint(
                fields=("farmer", "market", "produce", "transaction_date"),
                name="unique_produce_per_market_date",
                violation_error_message="Transaction already exist",
            ),
        ),
    ]
