# Generated by Django 5.1.1 on 2024-09-30 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0008_alter_farmersinputtransaction_farmer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="points_earned",
            field=models.IntegerField(
                editable=False, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="points_earned",
            field=models.IntegerField(
                editable=False, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
