# Generated by Django 5.1 on 2024-08-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0009_remove_farmersmarkettransaction_unique_transaction_id_and_more",
        ),
        ("market", "0003_alter_contactperson_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farmersmarkettransaction",
            name="unique_produce_per_market_date",
        ),
        migrations.RemoveField(
            model_name="farmersmarkettransaction",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="farmersmarkettransaction",
            name="updated_on",
        ),
        migrations.AddConstraint(
            model_name="farmersmarkettransaction",
            constraint=models.UniqueConstraint(
                fields=("farmer", "market", "produce", "transaction_date"),
                name="unique_mkt_transaction",
                violation_error_message="Transaction already exist",
            ),
        ),
    ]
