# Generated by Django 5.1.1 on 2024-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0010_alter_farmer_has_input_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="has_input_transaction",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="has_market_transaction",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
