# Generated by Django 5.1 on 2024-08-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0010_remove_farmersmarkettransaction_unique_produce_per_market_date_and_more",
        ),
        ("market", "0003_alter_contactperson_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farmersmarkettransaction",
            name="unique_mkt_transaction",
        ),
        migrations.AddConstraint(
            model_name="farmersmarkettransaction",
            constraint=models.UniqueConstraint(
                fields=("produce", "farmer", "market", "transaction_date"),
                name="unique_mkt_transaction",
                violation_error_message="Transaction already exist",
            ),
        ),
    ]
