# Generated by Django 5.1.1 on 2024-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0010_remove_farmersmarkettransaction_unique_farmersmarkettransaction_produce_farmer_market_transaction_da",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="transaction_date",
            field=models.DateField(),
        ),
    ]
