# Generated by Django 5.1 on 2024-08-29 21:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0011_remove_farmersmarkettransaction_unique_mkt_transaction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="cultivatedfield",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="cultivatedfieldhistory",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="farmerscooperative",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="farmersinputtransaction",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="fieldextensionofficer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
    ]
