# Generated by Django 5.1.1 on 2024-09-19 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0011_alter_farmersmarkettransaction_transaction_date"),
        ("market", "0005_alter_marketday_mkt_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farmersmarkettransaction",
            name="unique_farmersmarkettransaction_produce_farmer_market_transaction_date",
        ),
        migrations.RemoveField(
            model_name="farmersinputtransaction",
            name="receipt_redemption_date",
        ),
        migrations.AddField(
            model_name="farmersinputtransaction",
            name="transaction_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="farmersmarkettransaction",
            constraint=models.UniqueConstraint(
                fields=("produce", "farmer", "market", "transaction_date"),
                name="unique_mkt_transaction",
            ),
        ),
    ]
