# Generated by Django 5.1.1 on 2024-09-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0012_remove_farmersmarkettransaction_unique_farmersmarkettransaction_produce_farmer_market_transaction_da",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmersinputtransaction",
            old_name="transaction_date",
            new_name="receipt_redemption_date",
        ),
    ]
