# Generated by Django 5.1 on 2024-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0012_badge_phone_cultivatedfield_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmersinputtransaction",
            old_name="created_on",
            new_name="receipt_redemption_date",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="farmerscooperative",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="farmersinputtransaction",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="farmersinputtransaction",
            name="redemption_date",
        ),
        migrations.RemoveField(
            model_name="farmersinputtransaction",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="fieldextensionofficer",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="farmersmarkettransaction",
            name="transaction_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
