# Generated by Django 5.1.1 on 2024-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0013_rename_transaction_date_farmersinputtransaction_receipt_redemption_date",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farmersinputtransaction",
            name="unique_receipt_identifier",
        ),
        migrations.AddConstraint(
            model_name="farmersinputtransaction",
            constraint=models.UniqueConstraint(
                fields=("receipt_number", "farmer", "receipt_redemption_date"),
                name="unique_receipt_identifier",
            ),
        ),
    ]
