# Generated by Django 5.1 on 2024-08-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0013_rename_created_on_farmersinputtransaction_receipt_redemption_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cultivatedfieldhistory",
            name="unique_cultivated_field_history",
        ),
        migrations.RemoveField(
            model_name="badge",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="badge",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="badge",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="cultivatedfield",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="cultivatedfield",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="cultivatedfield",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="cultivatedfieldhistory",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="cultivatedfieldhistory",
            name="updated_on",
        ),
        migrations.AddConstraint(
            model_name="cultivatedfieldhistory",
            constraint=models.UniqueConstraint(
                fields=("cultivated_field",), name="unique_cultivated_field_history"
            ),
        ),
    ]
