# Generated by Django 5.1 on 2024-08-29 22:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmers",
            "0014_remove_cultivatedfieldhistory_unique_cultivated_field_history_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="farmerscooperative",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="fieldextensionofficer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None
            ),
        ),
    ]
