# Generated by Django 5.1.1 on 2024-09-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0015_remove_farmer_verification_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agrovendor",
            name="contact_phone",
        ),
    ]
