# Generated by Django 5.1.1 on 2024-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0016_remove_agrovendor_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmersinputtransaction",
            name="receipt_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
