# Generated by Django 5.1 on 2024-08-29 23:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0017_alter_farmer_phone_alter_farmerscooperative_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region="NG", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="farmerscooperative",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region="NG", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fieldextensionofficer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region="NG", unique=True
            ),
        ),
    ]
