# Generated by Django 5.1 on 2024-08-25 07:18

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "farmers",
            "0011_remove_farmersmarkettransaction_unique_mkt_transaction_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Agrochemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "agrochemical_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRE", "Pre Emergence Herbicide"),
                            ("POS", "Post Emergence Herbicide"),
                            ("PES", "Pesticide"),
                            ("INT", "Insecticide"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "name__iexact",
                                django.db.models.functions.text.Lower("name"),
                            )
                        ),
                        fields=("agrochemical_name", "name"),
                        name="unique_agrochemical_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Fertilizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "fertilizer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NPK", "Npk"),
                            ("UREA", "Urea"),
                            ("SSP", "Single Super Phosphate"),
                            ("MP", "Muriate of Potash"),
                            ("DP", "Diammonium Phosphate"),
                            ("OTHER", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "fertilizer_blend",
                    models.CharField(default="20:10:10", max_length=255),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "name__iexact",
                                django.db.models.functions.text.Lower("name"),
                            )
                        ),
                        fields=("name", "fertilizer_type", "fertilizer_blend"),
                        name="unique_fertilizer",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InputPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "kilogram"),
                            ("ltr", "liter"),
                            ("bag", "bag"),
                            ("acre", "Acres"),
                            ("ha", "hectare"),
                            ("packet", "per packet"),
                            ("bottle", "per bottle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mechanization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLOUGH", "Disc Plough"),
                            ("HARROW", "Harrow"),
                            ("RIDGE", "Ridge"),
                            ("FERT_APP", "Fertilizer Application"),
                            ("PLANTING", "Planting"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_mechanization_operation"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Seed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "seed_variety",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("gmo", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAIZE", "Maize"),
                            ("COWPEA", "Cowpea"),
                            ("SOYBEAN", "Soybean"),
                            ("RICE", "Rice"),
                            ("SORGHUM", "Sorghum"),
                            ("MILLET", "Millet"),
                            ("GROUNDNUT", "Groundnut"),
                            ("COTTON", "Cotton"),
                            ("SESAME", "Sesame"),
                            ("YAM", "Yam"),
                            ("CASSAVA", "Cassava"),
                            ("TOMATO", "Tomatoe"),
                            ("PEPPER", "Pepper"),
                            ("OTHER", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "seed_variety__iexact",
                                django.db.models.functions.text.Lower("seed_variety"),
                            )
                        ),
                        fields=("name", "seed_variety"),
                        name="unique_seed",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubsidizedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SEED", "Seed"),
                            ("FERT", "Fertilizer"),
                            ("MECH", "Mechanization"),
                            ("CHEM", "Chemical"),
                        ],
                        max_length=255,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubsidyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("objective", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "sponsor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "program_director",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "legislation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number_of_beneficiaries", models.SmallIntegerField(default=0)),
                (
                    "sponsor_type",
                    models.CharField(
                        choices=[
                            ("STATE", "State Government"),
                            ("NATIONAL", "National Government"),
                            ("NGO", "Non Governmental Organization"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "budget_in_naira",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=40, null=True
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cities_light.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cities_light.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubsidyInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("redemption_date", models.DateField(auto_now_add=True)),
                (
                    "redemption_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, editable=False, max_digits=7
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subsidy_intance",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subsidy_intance",
                        to="subsidy.subsidizeditem",
                    ),
                ),
                (
                    "subsidy_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_intance",
                        to="subsidy.subsidyprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubsidyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("50"), max_digits=4
                    ),
                ),
                (
                    "subsidized_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_rate",
                        to="subsidy.subsidizeditem",
                    ),
                ),
                (
                    "subsidy_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_rate",
                        to="subsidy.subsidyprogram",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subsidizeditem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="subsidy_sub_content_e2e079_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsidizeditem",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"), name="unique_subsidized_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="subsidyinstance",
            constraint=models.UniqueConstraint(
                fields=("farmer", "item", "subsidy_program"),
                name="unique_farmer_subsidy",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsidyrate",
            constraint=models.UniqueConstraint(
                fields=("subsidy_program", "subsidized_item"),
                name="unique_subsidy_rate",
            ),
        ),
    ]
