# Generated by Django 5.1 on 2024-09-02 14:36

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agrochemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRE", "Pre Emergence Herbicide"),
                            ("POS", "Post Emergence Herbicide"),
                            ("PES", "Pesticide"),
                            ("INT", "Insecticide"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "brand__iexact",
                                django.db.models.functions.text.Lower("brand"),
                            )
                        ),
                        fields=("brand", "type"),
                        name="unique_agrochemical_brand",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Fertilizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("brand", models.CharField(max_length=100, unique=True)),
                (
                    "fertilizer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NPK", "Npk"),
                            ("UREA", "Urea"),
                            ("SSP", "Single Super Phosphate"),
                            ("MP", "Muriate of Potash"),
                            ("DP", "Diammonium Phosphate"),
                            ("OTHER", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fertilizer_blend",
                    models.CharField(default="20:10:10", max_length=255),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "brand__iexact",
                                django.db.models.functions.text.Lower("brand"),
                            )
                        ),
                        fields=("brand", "fertilizer_type", "fertilizer_blend"),
                        name="unique_fertilizer",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InputPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "kilogram"),
                            ("ltr", "liter"),
                            ("bag", "bag"),
                            ("acre", "Acres"),
                            ("ha", "hectare"),
                            ("packet", "per packet"),
                            ("bottle", "per bottle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mechanization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLOUGH", "Disc Plough"),
                            ("HARROW", "Harrow"),
                            ("RIDGE", "Ridge"),
                            ("FERT_APP", "Fertilizer Application"),
                            ("PLANTING", "Planting"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation",), name="unique_mechanization_operation"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Seed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("brand", models.CharField(default="Seedco", max_length=100)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAIZE", "Maize"),
                            ("COWPEA", "Cowpea"),
                            ("SOYBEAN", "Soybean"),
                            ("RICE", "Rice"),
                            ("SORGHUM", "Sorghum"),
                            ("MILLET", "Millet"),
                            ("GROUNDNUT", "Groundnut"),
                            ("COTTON", "Cotton"),
                            ("SESAME", "Sesame"),
                            ("YAM", "Yam"),
                            ("CASSAVA", "Cassava"),
                            ("TOMATO", "Tomatoe"),
                            ("PEPPER", "Pepper"),
                            ("OTHER", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "seed_variety",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("gmo", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "seed_variety__iexact",
                                django.db.models.functions.text.Lower("seed_variety"),
                            )
                        ),
                        fields=("brand", "name", "seed_variety"),
                        name="unique_seed",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubsidizedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SEED", "Seed"),
                            ("FERTILIZER", "Fertilizer"),
                            ("MECHANIZATION", "Mechanization"),
                            ("AGROCHEMICAL", "Chemical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "kilogram"),
                            ("ltr", "liter"),
                            ("bag", "bag"),
                            ("acre", "Acres"),
                            ("ha", "hectare"),
                            ("packet", "per packet"),
                            ("bottle", "per bottle"),
                        ],
                        default="ltr",
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubsidyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("implementation_details", models.TextField(blank=True, null=True)),
                (
                    "sponsor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("STATE", "State"), ("NATIONAL", "National")],
                        default="NATIONAL",
                        max_length=10,
                    ),
                ),
                ("target_num_of_beneficiaries", models.SmallIntegerField(default=200)),
                (
                    "budget_in_naira",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=40, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cities_light.country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cities_light.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubsidyInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("redemption_date", models.DateField(auto_now_add=True)),
                (
                    "redemption_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, editable=False, max_digits=7
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subsidy_intance",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_intance",
                        to="subsidy.subsidizeditem",
                    ),
                ),
                (
                    "subsidy_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_intance",
                        to="subsidy.subsidyprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubsidyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("50"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "subsidized_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_rate",
                        to="subsidy.subsidizeditem",
                    ),
                ),
                (
                    "subsidy_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_rate",
                        to="subsidy.subsidyprogram",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subsidizeditem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="subsidy_sub_content_e2e079_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsidizeditem",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"), name="unique_subsidized_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="subsidyinstance",
            constraint=models.UniqueConstraint(
                fields=("farmer", "item", "subsidy_program"),
                name="unique_farmer_subsidy",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsidyrate",
            constraint=models.UniqueConstraint(
                fields=("subsidy_program", "subsidized_item"),
                name="unique_subsidy_rate",
            ),
        ),
    ]
