# Generated by Django 5.1.1 on 2024-09-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subsidy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidizeditem",
            name="item_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
