# Generated by Django 5.1.1 on 2024-09-19 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
        ("subsidy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidyinstance",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsidy_instances",
                to="farmers.farmer",
            ),
        ),
    ]
