# Generated by Django 5.1 on 2024-08-29 21:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subsidy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agrochemical",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="fertilizer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="inputpricehistory",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="mechanization",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="seed",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="subsidizeditem",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="subsidyinstance",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="subsidyprogram",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="subsidyrate",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=11, null=True, region=None
            ),
        ),
    ]
