# Generated by Django 5.1.1 on 2024-09-19 17:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0016_remove_agrovendor_contact_phone"),
        ("subsidy", "0002_subsidizeditem_item_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsidyInstanceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="subsidyinstance",
            name="items",
        ),
        migrations.RemoveField(
            model_name="subsidyinstance",
            name="quantity",
        ),
        migrations.AddField(
            model_name="subsidizeditem",
            name="item_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subsidizeditem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kilogram"),
                    ("50kg", "50 kilogram"),
                    ("ltr", "liter"),
                    ("ha", "hectare"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subsidyinstance",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subsidy_instances",
                to="farmers.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="subsidyinstance",
            name="subsidy_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsidy_instances",
                to="subsidy.subsidyprogram",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsidizeditem",
            constraint=models.UniqueConstraint(
                fields=("item_type", "item_name"), name="unique_subsidized_item"
            ),
        ),
        migrations.AddField(
            model_name="subsidyinstanceitem",
            name="subsidized_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsidy_instance_items",
                to="subsidy.subsidizeditem",
            ),
        ),
        migrations.AddField(
            model_name="subsidyinstanceitem",
            name="subsidy_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsidy_instance_items",
                to="subsidy.subsidyinstance",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subsidyinstanceitem",
            unique_together={("subsidy_instance", "subsidized_item")},
        ),
    ]
