# Generated by Django 5.1.1 on 2024-09-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subsidy", "0003_subsidyinstanceitem_remove_subsidyinstance_items_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fertilizer",
            name="unique_fertilizer",
        ),
        migrations.AddConstraint(
            model_name="fertilizer",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "fertilizer_type", "fertilizer_blend"),
                name="unique_fertilizer",
            ),
        ),
    ]
