# Generated by Django 5.1 on 2024-08-29 23:11

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subsidy", "0004_alter_agrochemical_phone_alter_fertilizer_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agrochemical",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fertilizer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="inputpricehistory",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="mechanization",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="seed",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subsidizeditem",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subsidyinstance",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subsidyprogram",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subsidyrate",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None, unique=True
            ),
        ),
    ]
