# Generated by Django 5.1.1 on 2024-09-19 17:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subsidy", "0004_remove_fertilizer_unique_fertilizer_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fertilizer",
            name="unique_fertilizer",
        ),
        migrations.AlterField(
            model_name="fertilizer",
            name="manufacturer",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="fertilizer",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "manufacturer__iexact",
                        django.db.models.functions.text.Lower("manufacturer"),
                    )
                ),
                fields=("manufacturer", "fertilizer_type", "fertilizer_blend"),
                name="unique_fertilizer",
            ),
        ),
    ]
