# Generated by Django 5.1.1 on 2024-09-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subsidy", "0005_remove_fertilizer_unique_fertilizer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agrochemical",
            name="price",
        ),
        migrations.RemoveField(
            model_name="agrochemical",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="fertilizer",
            name="price",
        ),
        migrations.RemoveField(
            model_name="fertilizer",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="mechanizationoperation",
            name="price",
        ),
        migrations.RemoveField(
            model_name="mechanizationoperation",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="seed",
            name="price",
        ),
        migrations.RemoveField(
            model_name="seed",
            name="unit",
        ),
    ]
