# Generated by Django 5.1.1 on 2024-09-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subsidy", "0006_remove_agrochemical_price_remove_agrochemical_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subsidyprogram",
            name="target_num_of_beneficiaries",
        ),
    ]
