# Generated by Django 5.1 on 2024-08-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subsidy", "0007_alter_agrochemical_phone_alter_fertilizer_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inputpricehistory",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="inputpricehistory",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="inputpricehistory",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="subsidyprogram",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="subsidyprogram",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="subsidyprogram",
            name="updated_on",
        ),
    ]
