# Generated by Django 5.1 on 2024-08-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_on",
        ),
    ]
