# Generated by Django 5.1.1 on 2024-10-01 22:45

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="07069483726", max_length=128, region=None, unique=True
            ),
            preserve_default=False,
        ),
    ]
