# Generated by Django 5.1 on 2024-08-29 22:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0002_contact_delete_waitlistentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=13, null=True, region=None
            ),
        ),
    ]
