# Generated by Django 5.1 on 2024-08-29 23:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0006_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=14, null=True, region="NG", unique=True
            ),
        ),
    ]
