# Generated by Django 5.1 on 2024-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0007_alter_contact_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
