# Generated by Django 5.1 on 2024-09-01 00:06

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0008_remove_contact_created_at_alter_contact_created_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="updated_on",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="created_on",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=14, null=True, region=None, unique=True
            ),
        ),
    ]
